name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn type-check

      - name: Format check
        run: yarn format:check

      - name: Run tests (optional for now)
        run: |
          if jq -e '.scripts.test' package.json >/dev/null; then
            yarn test
          else
            echo "⚠️ No test script found in package.json - skipping tests"
          fi
        continue-on-error: true

      - name: Build
        run: yarn build
